// HEY, NO CHEATING!
let songs = [
{url:"https://soundcloud.com/kubbi/juggernaut",answer:"Kubbi 🌲 - Juggernaut"},
{url:"https://soundcloud.com/kubbi/kubbi-ember",answer:"Kubbi 🌲 - Ember"},
{url:"https://soundcloud.com/kubbi/indolence-renovation-mix",answer:"Kubbi 🌲 - Indolence (Renovation Mix)"},
{url:"https://soundcloud.com/kubbi/gravity",answer:"Kubbi 🌲 - Gravity"},
{url:"https://soundcloud.com/kubbi/antlers",answer:"Kubbi 🌲 - Antlers"},
{url:"https://soundcloud.com/kubbi/overworld",answer:"Kubbi 🌲 - Overworld"},
{url:"https://soundcloud.com/kubbi/planet-iii-mesosphere",answer:"Kubbi 🌲 - Planet III (Mesosphere)"},
{url:"https://soundcloud.com/kubbi/kubbi-planet-i-troposphere",answer:"Kubbi 🌲 - Planet I (Troposphere)"},
{url:"https://soundcloud.com/kubbi/indolence-1",answer:"Kubbi 🌲 - Indolence"},
{url:"https://soundcloud.com/kubbi/cascade",answer:"Kubbi 🌲 - Cascade"},
{url:"https://soundcloud.com/kubbi/up-in-my-jam-all-of-a-sudden",answer:"Kubbi 🌲 - Up In My Jam (All Of A Sudden)"},
{url:"https://soundcloud.com/kubbi/firelight",answer:"Kubbi 🌲 - Firelight"},
{url:"https://soundcloud.com/kubbi/careless-whisper",answer:"Kubbi 🌲 - Careless Whisper"},
{url:"https://soundcloud.com/kubbi/algebraic",answer:"Kubbi 🌲 - Algebraic!"},
{url:"https://soundcloud.com/kubbi/stjernebilde-kubbis-flip",answer:"Kubbi 🌲 - Stjernebilde (Kubbi's Flip)"},
{url:"https://soundcloud.com/kubbi/warmhugsincourt",answer:"Kubbi 🌲 - Warm Hugs in Court"},
{url:"https://soundcloud.com/kubbi/paracet",answer:"Kubbi 🌲 - Paracet"},
{url:"https://soundcloud.com/kubbi/kubbi-damage",answer:"Kubbi 🌲 - Damage"},
{url:"https://soundcloud.com/kubbi/concrete-renovation-mix",answer:"Kubbi 🌲 - Concrete (Renovation Mix)"},
{url:"https://soundcloud.com/kubbi/retrospect",answer:"Kubbi - Retrospect"},
{url:"https://soundcloud.com/kubbi/formed-by-glaciers",answer:"Kubbi 🌲 - Formed By Glaciers"},
{url:"https://soundcloud.com/kubbi/void-pt-2-renovation-mix",answer:"Kubbi 🌲 - Void Pt 2 (Renovation Mix)"},
{url:"https://soundcloud.com/kubbi/pathfinder",answer:"Kubbi 🌲 - Pathfinder"},
{url:"https://soundcloud.com/kubbi/television-for-robots",answer:"Kubbi 🌲 - Television For Robots"},
{url:"https://soundcloud.com/kubbi/something-new",answer:"Kubbi 🌲 - Something New"},
{url:"https://soundcloud.com/kubbi/spiritdancer",answer:"Kubbi 🌲 - Spiritdancer"},
{url:"https://soundcloud.com/kubbi/kubbi-planet-iv-ionosphere",answer:"Kubbi 🌲 - Planet IV (Ionosphere)"},
{url:"https://soundcloud.com/kubbi/ropes",answer:"Kubbi 🌲 - Ropes"},
{url:"https://soundcloud.com/kubbi/concrete-single",answer:"Kubbi 🌲 - Concrete"},
{url:"https://soundcloud.com/kubbi/dolphin-af",answer:"Kubbi - Dolphin Af"},
{url:"https://soundcloud.com/kubbi/bitpop",answer:"Kubbi 🌲 - Bitpop"},
{url:"https://soundcloud.com/kubbi/compass",answer:"Kubbi 🌲 - Compass"},
{url:"https://soundcloud.com/kubbi/indolence",answer:"Kubbi 🌲 - Indolence"},
{url:"https://soundcloud.com/kubbi/the-see-through-zone",answer:"Kubbi 🌲 - The See-Through Zone"},
{url:"https://soundcloud.com/kubbi/doomsday-afterparty",answer:"Kubbi 🌲 - Doomsday Afterparty"},
{url:"https://soundcloud.com/kubbi/circuithead",answer:"Kubbi 🌲 - Circuithead"},
{url:"https://soundcloud.com/kubbi/cartridge-read-description",answer:"Kubbi 🌲 - Cartridge"},
{url:"https://soundcloud.com/kubbi/motivation",answer:"Kubbi 🌲 - Motivation"},
{url:"https://soundcloud.com/kubbi/the-cairn",answer:"Kubbi 🌲 - The Cairn"},
{url:"https://soundcloud.com/kubbi/machinery",answer:"Kubbi 🌲 - Machinery"},
{url:"https://soundcloud.com/kubbi/wildcard",answer:"Kubbi - Wildcard"},
{url:"https://soundcloud.com/kubbi/kubbi-cronos",answer:"Kubbi 🌲 - Cronos"},
{url:"https://soundcloud.com/kubbi/taiga",answer:"Kubbi - TAIGA"},
{url:"https://soundcloud.com/kubbi/restoration",answer:"Kubbi 🌲 - Restoration"},
{url:"https://soundcloud.com/kubbi/kubbi-sleet",answer:"Kubbi 🌲 - Sleet"},
{url:"https://soundcloud.com/kubbi/the-hibernator",answer:"Kubbi 🌲 - The Hibernator"},
{url:"https://soundcloud.com/kubbi/plume",answer:"Kubbi - Plume"},
{url:"https://soundcloud.com/kubbi/the-spectator",answer:"Kubbi 🌲 - The Spectator"},
{url:"https://soundcloud.com/kubbi/outro-theme-binoftrash",answer:"Kubbi 🌲 - Outro Theme (Binoftrash)"},
{url:"https://soundcloud.com/kubbi/toaster",answer:"Kubbi 🌲 - Toaster"},
{url:"https://soundcloud.com/kubbi/tidal-force",answer:"Kubbi 🌲 - Tidal force"},
{url:"https://soundcloud.com/kubbi/escapist",answer:"Kubbi 🌲 - Escapist"},
{url:"https://soundcloud.com/kubbi/warm-hugs-in-court",answer:"Kubbi 🌲 - Warm Hugs in Court"},
{url:"https://soundcloud.com/kubbi/summits",answer:"Kubbi 🌲 - Summits"},
{url:"https://soundcloud.com/kubbi/acheron",answer:"Kubbi 🌲 - Acheron"},
{url:"https://soundcloud.com/kubbi/polarity-teslagrad-ost-remix",answer:"Kubbi 🌲 - Polarity (Teslagrad OST Remix)"},
{url:"https://soundcloud.com/kubbi/bright-matter",answer:"Kubbi 🌲 - Bright matter"},
{url:"https://soundcloud.com/kubbi/flicker",answer:"Kubbi 🌲 - Flicker"},
{url:"https://soundcloud.com/kubbi/kubbi-stalactite-from",answer:"Kubbi 🌲 - Stalactite (From 8BitWorld)"},
{url:"https://soundcloud.com/kubbi/slamajam-soundtrack-from-the",answer:"Kubbi 🌲 - Slamajam (Soundtrack from The Game of SPLEEF)"},
{url:"https://soundcloud.com/kubbi/slamacows-outro-jam",answer:"Kubbi 🌲 - Slamacow's Outro-Jam"},
{url:"https://soundcloud.com/kubbi/dj-cutman-powerglove-kubbimix",answer:"Kubbi 🌲 - Powerglove (Kubbimix)"},
{url:"https://soundcloud.com/kubbi/kubbi-mellow",answer:"Kubbi 🌲 - Mellow"},
{url:"https://soundcloud.com/kubbi/wake",answer:"Kubbi 🌲 - Wake"},
{url:"https://soundcloud.com/kubbi/disconnect",answer:"Kubbi 🌲 - Disconnect"},
{url:"https://soundcloud.com/kubbi/polar-bear-rides-merry",answer:"Kubbi 🌲 - Polar Bear Rides"},
{url:"https://soundcloud.com/kubbi/sunrise-new-beginning",answer:"Kubbi 🌲 - Sunrise (New Beginning)"},
{url:"https://soundcloud.com/kubbi/tidal-force-renovation-mix",answer:"Kubbi 🌲 - Tidal Force (Renovation Mix)"},
{url:"https://soundcloud.com/kubbi/corrosion-city",answer:"Kubbi 🌲 - Corrosion City"},
{url:"https://soundcloud.com/kubbi/i-inc",answer:"Kubbi 🌲 - I inc."},
{url:"https://soundcloud.com/kubbi/void-part-2",answer:"Kubbi 🌲 - Void part 2"},
{url:"https://soundcloud.com/kubbi/we-are-wired",answer:"Kubbi 🌲 - We are Wired"},
{url:"https://soundcloud.com/kubbi/last-save-loaded",answer:"Kubbi 🌲 - Last save loaded"},
{url:"https://soundcloud.com/kubbi/vitamin-b12",answer:"Kubbi 🌲 - Vitamin B12"},
{url:"https://soundcloud.com/kubbi/pewpewpew",answer:"Kubbi 🌲 - PewPewPew"},
{url:"https://soundcloud.com/kubbi/planet-ii-stratosphere",answer:"Kubbi 🌲 - Planet II (Stratosphere)"}
];
